### PR TITLE
Follow Faraday 1.0 breaking changes.

### PR DESCRIPTION
**Pull request by yasuyuki-baba**
- Follow Faraday 1.0 breaking changes.
https://github.com/lostisland/faraday/blob/v1.0-rc1/UPGRADING.md#others
- Update gemspec (Bundler)
- Bump Ruby versions for Travis CI

### CODE REVIEW

**Comment by yasuyuki-baba** [comment]
@umakoz Could you please check my changes?

**Review by umakoz — APPROVED** [review]
Sorry for keeping you waiting.
LGTM!!

**Comment by yasuyuki-baba** [comment]
@umakoz Thank you for merging!
I'm happy if you release a new version.

**Comment by umakoz** [comment]
@yasuyuki-baba I have released v0.1.1.
https://rubygems.org/gems/typetalk

**Comment by yasuyuki-baba** [comment]
@umakoz Thank you very much for your support!!

**Pull request merged**
